In [1]:
import utils
import householder as hh

import importlib
import numpy as np
importlib.reload(utils)
importlib.reload(hh)

<module 'householder' from 'C:\\Users\\Hideki\\Desktop\\Github\\unicamp\\MS512\\lib\\householder.py'>

# Inicializando uma matriz de hilbert

In [2]:
H = utils.getHilbert(13)
H

array([[ 1.        ,  0.5       ,  0.33333333,  0.25      ,  0.2       ,
         0.16666667,  0.14285714,  0.125     ,  0.11111111,  0.1       ,
         0.09090909,  0.08333333,  0.07692308],
       [ 0.5       ,  0.33333333,  0.25      ,  0.2       ,  0.16666667,
         0.14285714,  0.125     ,  0.11111111,  0.1       ,  0.09090909,
         0.08333333,  0.07692308,  0.07142857],
       [ 0.33333333,  0.25      ,  0.2       ,  0.16666667,  0.14285714,
         0.125     ,  0.11111111,  0.1       ,  0.09090909,  0.08333333,
         0.07692308,  0.07142857,  0.06666667],
       [ 0.25      ,  0.2       ,  0.16666667,  0.14285714,  0.125     ,
         0.11111111,  0.1       ,  0.09090909,  0.08333333,  0.07692308,
         0.07142857,  0.06666667,  0.0625    ],
       [ 0.2       ,  0.16666667,  0.14285714,  0.125     ,  0.11111111,
         0.1       ,  0.09090909,  0.08333333,  0.07692308,  0.07142857,
         0.06666667,  0.0625    ,  0.05882353],
       [ 0.16666667,  0.142857

In [3]:
utils.norma_mat1(H)

3.1801337551337552

# Fazendo a fatoração QR pela classe construida

In [4]:
house = hh.HouseHolder([1,2,3])
Q2, R2= house.getQR(H)

# Fazendo a fatoração QR pela lib do scipy

In [5]:
import scipy
import scipy.linalg

Q, R = scipy.linalg.qr(H)

# Comparando as matrizes Q

In [6]:
print("Matriz pelo scipy")
print(Q.round(4))
print('\n')
print("Matriz pela classe")
print(Q2.round(4))
print('\n')
print("Diferença")
print((Q-Q2).round(4))

Matriz pelo scipy
[[ -7.97900000e-01   5.53400000e-01   2.25600000e-01  -7.58000000e-02
    2.23000000e-02  -5.80000000e-03  -1.40000000e-03   3.00000000e-04
   -1.00000000e-04  -0.00000000e+00  -0.00000000e+00   0.00000000e+00
   -0.00000000e+00]
 [ -3.98900000e-01  -2.29500000e-01  -6.38200000e-01   5.28100000e-01
   -2.90600000e-01   1.24100000e-01   4.35000000e-02  -1.29000000e-02
    3.20000000e-03   7.00000000e-04   1.00000000e-04  -0.00000000e+00
    0.00000000e+00]
 [ -2.66000000e-01  -3.21700000e-01  -3.09800000e-01  -2.61200000e-01
    5.66100000e-01  -4.90800000e-01  -2.86400000e-01   1.26900000e-01
   -4.46000000e-02  -1.26000000e-02  -2.80000000e-03   5.00000000e-04
   -1.00000000e-04]
 [ -1.99500000e-01  -3.17200000e-01  -7.04000000e-02  -4.10700000e-01
    1.77500000e-01   3.32100000e-01   5.41400000e-01  -4.31700000e-01
    2.34400000e-01   9.43000000e-02   2.86000000e-02  -6.30000000e-03
    9.00000000e-04]
 [ -1.59600000e-01  -2.94200000e-01   7.18000000e-02  -3.33500

In [9]:
print("Matriz pelo scipy")
print(R.round(4))
print('\n')
print("Matriz pela classe")
print(R2.round(4))
print('\n')
print("Diferença")
print((R-R2).round(4))

Matriz pelo scipy
[[ -1.25340000e+00  -7.40900000e-01  -5.43300000e-01  -4.34200000e-01
   -3.63800000e-01  -3.14100000e-01  -2.76900000e-01  -2.47900000e-01
   -2.24700000e-01  -2.05500000e-01  -1.89500000e-01  -1.75800000e-01
   -1.64100000e-01]
 [  0.00000000e+00  -1.64600000e-01  -1.87200000e-01  -1.84500000e-01
   -1.75600000e-01  -1.65500000e-01  -1.55600000e-01  -1.46300000e-01
   -1.37900000e-01  -1.30300000e-01  -1.23400000e-01  -1.17100000e-01
   -1.11500000e-01]
 [  0.00000000e+00   0.00000000e+00   1.52000000e-02   2.54000000e-02
    3.15000000e-02   3.51000000e-02   3.71000000e-02   3.81000000e-02
    3.84000000e-02   3.83000000e-02   3.79000000e-02   3.74000000e-02
    3.67000000e-02]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.20000000e-03
    2.60000000e-03   3.90000000e-03   4.90000000e-03   5.80000000e-03
    6.50000000e-03   7.00000000e-03   7.40000000e-03   7.70000000e-03
    7.90000000e-03]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000

# Testando propriedades de Q

In [10]:
np.dot(Q,utils.transposta(Q)).round(4)

array([[ 1.,  0.,  0.,  0.,  0.,  0., -0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0., -0., -0., -0., -0.,  0., -0.,  0., -0.,  0., -0.],
       [ 0.,  0.,  1.,  0., -0., -0., -0.,  0.,  0.,  0.,  0., -0., -0.],
       [ 0., -0.,  0.,  1., -0.,  0.,  0., -0., -0., -0., -0.,  0.,  0.],
       [ 0., -0., -0., -0.,  1., -0., -0., -0.,  0.,  0.,  0., -0.,  0.],
       [ 0., -0., -0.,  0., -0.,  1.,  0.,  0., -0.,  0., -0.,  0., -0.],
       [-0., -0., -0.,  0., -0.,  0.,  1., -0.,  0.,  0.,  0., -0., -0.],
       [ 0.,  0.,  0., -0., -0.,  0., -0.,  1., -0.,  0.,  0., -0., -0.],
       [ 0., -0.,  0., -0.,  0., -0.,  0., -0.,  1., -0., -0.,  0.,  0.],
       [ 0.,  0.,  0., -0.,  0.,  0.,  0.,  0., -0.,  1.,  0., -0.,  0.],
       [ 0., -0.,  0., -0.,  0., -0.,  0.,  0., -0.,  0.,  1.,  0., -0.],
       [ 0.,  0., -0.,  0., -0.,  0., -0., -0.,  0., -0.,  0.,  1.,  0.],
       [ 0.,  0., -0.,  0.,  0., -0., -0., -0.,  0.,  0., -0.,  0.,  1.]])

# Nossa fatoração está boa

# Testando a resolução de sistema linear

In [17]:
import utils
import householder as hh

import importlib
import numpy as np
importlib.reload(utils)
importlib.reload(hh)

<module 'householder' from 'C:\\Users\\Hideki\\Desktop\\Github\\unicamp\\MS512\\lib\\householder.py'>

In [102]:
i = 3
H = utils.getHilbert(i)
H

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.5       ,  0.33333333,  0.25      ],
       [ 0.33333333,  0.25      ,  0.2       ]])

In [93]:
house = hh.HouseHolder(H)

In [94]:
inv_house = house.resolve_sistema(np.eye(i))
inv_house

array([[  2.50000000e+01,  -3.00000000e+02,   1.05000000e+03,
         -1.40000000e+03,   6.30000000e+02],
       [ -3.00000000e+02,   4.80000000e+03,  -1.89000000e+04,
          2.68800000e+04,  -1.26000000e+04],
       [  1.05000000e+03,  -1.89000000e+04,   7.93800000e+04,
         -1.17600000e+05,   5.67000000e+04],
       [ -1.40000000e+03,   2.68800000e+04,  -1.17600000e+05,
          1.79200000e+05,  -8.82000000e+04],
       [  6.30000000e+02,  -1.26000000e+04,   5.67000000e+04,
         -8.82000000e+04,   4.41000000e+04]])

In [101]:
np.dot(H,inv_house).round(11)

array([[  1.00000000e+00,   0.00000000e+00,  -0.00000000e+00,
          1.00000000e-11,  -0.00000000e+00],
       [ -0.00000000e+00,   1.00000000e+00,  -0.00000000e+00,
          1.00000000e-11,  -0.00000000e+00],
       [ -0.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          0.00000000e+00,  -0.00000000e+00],
       [ -0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          1.00000000e+00,  -0.00000000e+00],
       [ -0.00000000e+00,  -0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   1.00000000e+00]])

In [22]:
Q, R = scipy.linalg.qr(H)

In [23]:
print(Q)
print('\n')
print(R)

[[-0.8265843   0.53335463 -0.17530535  0.03910207  0.00550474]
 [-0.41329215 -0.37405354  0.7172624  -0.40334521 -0.11009471]
 [-0.2755281  -0.46294598  0.05766473  0.67896462  0.49542619]
 [-0.20664607 -0.44331911 -0.35262561  0.20615371 -0.77066296]
 [-0.16531686 -0.40591376 -0.57195511 -0.57644719  0.38533148]]


[[ -1.20979796e+00  -6.88820248e-01  -4.92014463e-01  -3.85411329e-01
   -3.17759341e-01]
 [  0.00000000e+00  -1.30059810e-01  -1.40191904e-01  -1.32700236e-01
   -1.22322889e-01]
 [  0.00000000e+00   0.00000000e+00  -8.06537859e-03  -1.26325450e-02
   -1.49082870e-02]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00  -3.38121669e-04
   -6.89314703e-04]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    8.73767527e-06]]


In [24]:
inf = np.linalg.solve(R, np.dot(utils.transposta(Q),np.eye(i)))
inf

array([[  2.50000000e+01,  -3.00000000e+02,   1.05000000e+03,
         -1.40000000e+03,   6.30000000e+02],
       [ -3.00000000e+02,   4.80000000e+03,  -1.89000000e+04,
          2.68800000e+04,  -1.26000000e+04],
       [  1.05000000e+03,  -1.89000000e+04,   7.93800000e+04,
         -1.17600000e+05,   5.67000000e+04],
       [ -1.40000000e+03,   2.68800000e+04,  -1.17600000e+05,
          1.79200000e+05,  -8.82000000e+04],
       [  6.30000000e+02,  -1.26000000e+04,   5.67000000e+04,
         -8.82000000e+04,   4.41000000e+04]])

In [25]:
np.dot(H,inf).round(4)

array([[ 1.,  0., -0.,  0., -0.],
       [ 0.,  1.,  0., -0.,  0.],
       [ 0., -0.,  1.,  0.,  0.],
       [ 0., -0.,  0.,  1.,  0.],
       [ 0., -0.,  0., -0.,  1.]])

In [26]:
invof = np.linalg.solve(H,np.eye(i)) 
invof

array([[  2.50000000e+01,  -3.00000000e+02,   1.05000000e+03,
         -1.40000000e+03,   6.30000000e+02],
       [ -3.00000000e+02,   4.80000000e+03,  -1.89000000e+04,
          2.68800000e+04,  -1.26000000e+04],
       [  1.05000000e+03,  -1.89000000e+04,   7.93800000e+04,
         -1.17600000e+05,   5.67000000e+04],
       [ -1.40000000e+03,   2.68800000e+04,  -1.17600000e+05,
          1.79200000e+05,  -8.82000000e+04],
       [  6.30000000e+02,  -1.26000000e+04,   5.67000000e+04,
         -8.82000000e+04,   4.41000000e+04]])

In [27]:
np.dot(H,invof).round(4)

array([[ 1., -0.,  0.,  0., -0.],
       [ 0.,  1., -0., -0., -0.],
       [ 0., -0.,  1.,  0.,  0.],
       [ 0., -0.,  0.,  1.,  0.],
       [-0.,  0., -0.,  0.,  1.]])

# Número de condicionamento

In [51]:
importlib.reload(utils)
i = 1000
H = utils.getHilbert(i)
H

array([[  1.00000000e+00,   5.00000000e-01,   3.33333333e-01, ...,
          1.00200401e-03,   1.00100100e-03,   1.00000000e-03],
       [  5.00000000e-01,   3.33333333e-01,   2.50000000e-01, ...,
          1.00100100e-03,   1.00000000e-03,   9.99000999e-04],
       [  3.33333333e-01,   2.50000000e-01,   2.00000000e-01, ...,
          1.00000000e-03,   9.99000999e-04,   9.98003992e-04],
       ..., 
       [  1.00200401e-03,   1.00100100e-03,   1.00000000e-03, ...,
          5.01253133e-04,   5.01002004e-04,   5.00751127e-04],
       [  1.00100100e-03,   1.00000000e-03,   9.99000999e-04, ...,
          5.01002004e-04,   5.00751127e-04,   5.00500501e-04],
       [  1.00000000e-03,   9.99000999e-04,   9.98003992e-04, ...,
          5.00751127e-04,   5.00500501e-04,   5.00250125e-04]])

In [ ]:
house = hh.HouseHolder(H)
inv_house = house.resolve_sistema(np.eye(i))
inv_house

In [ ]:
np.dot(H,inv_house)

In [ ]:
Q, R = house.getQR(H)

In [ ]:
Q

In [ ]:
R

In [ ]:
np.dot(utils.transposta(Q),Q).round(4)

In [44]:
K1 = utils.norma_mat1(inv_house)*utils.norma_mat1(H)
K1

3.9859338317128876e+19

In [45]:
utils.norma_mat1(H[:,0])

5.1873775176396206

In [46]:
sum([np.abs(v) for v in H[:,0]])

5.1873775176396206

In [47]:
for k in range(i):
    for j in range(i):
        if(k!=j):
            ni = utils.norma_mat1(H[:,k])
            nj = utils.norma_mat1(H[:,j])

            cond = ni/nj

            if(K1 > cond):
                print(f"\nK1 é maior que a coluna {k} pela coluna {j}, K1 vale {K1.round(4)} e cond vale {cond.round(4)}\n")
            else:
                print("nop")


K1 é maior que a coluna 0 pela coluna 1, K1 vale 3.985933831712888e+19 e cond vale 1.2359


K1 é maior que a coluna 0 pela coluna 2, K1 vale 3.985933831712888e+19 e cond vale 1.3993


K1 é maior que a coluna 0 pela coluna 3, K1 vale 3.985933831712888e+19 e cond vale 1.5332


K1 é maior que a coluna 0 pela coluna 4, K1 vale 3.985933831712888e+19 e cond vale 1.6504


K1 é maior que a coluna 0 pela coluna 5, K1 vale 3.985933831712888e+19 e cond vale 1.7569


K1 é maior que a coluna 0 pela coluna 6, K1 vale 3.985933831712888e+19 e cond vale 1.8557


K1 é maior que a coluna 0 pela coluna 7, K1 vale 3.985933831712888e+19 e cond vale 1.9488


K1 é maior que a coluna 0 pela coluna 8, K1 vale 3.985933831712888e+19 e cond vale 2.0374


K1 é maior que a coluna 0 pela coluna 9, K1 vale 3.985933831712888e+19 e cond vale 2.1223


K1 é maior que a coluna 0 pela coluna 10, K1 vale 3.985933831712888e+19 e cond vale 2.2043


K1 é maior que a coluna 0 pela coluna 11, K1 vale 3.985933831712888e+19 e cond


K1 é maior que a coluna 8 pela coluna 10, K1 vale 3.985933831712888e+19 e cond vale 1.0819


K1 é maior que a coluna 8 pela coluna 11, K1 vale 3.985933831712888e+19 e cond vale 1.121


K1 é maior que a coluna 8 pela coluna 12, K1 vale 3.985933831712888e+19 e cond vale 1.1589


K1 é maior que a coluna 8 pela coluna 13, K1 vale 3.985933831712888e+19 e cond vale 1.196


K1 é maior que a coluna 8 pela coluna 14, K1 vale 3.985933831712888e+19 e cond vale 1.2322


K1 é maior que a coluna 8 pela coluna 15, K1 vale 3.985933831712888e+19 e cond vale 1.2678


K1 é maior que a coluna 8 pela coluna 16, K1 vale 3.985933831712888e+19 e cond vale 1.3028


K1 é maior que a coluna 8 pela coluna 17, K1 vale 3.985933831712888e+19 e cond vale 1.3372


K1 é maior que a coluna 8 pela coluna 18, K1 vale 3.985933831712888e+19 e cond vale 1.3711


K1 é maior que a coluna 8 pela coluna 19, K1 vale 3.985933831712888e+19 e cond vale 1.4045


K1 é maior que a coluna 8 pela coluna 20, K1 vale 3.985933831712888e+19


K1 é maior que a coluna 18 pela coluna 13, K1 vale 3.985933831712888e+19 e cond vale 0.8723


K1 é maior que a coluna 18 pela coluna 14, K1 vale 3.985933831712888e+19 e cond vale 0.8987


K1 é maior que a coluna 18 pela coluna 15, K1 vale 3.985933831712888e+19 e cond vale 0.9247


K1 é maior que a coluna 18 pela coluna 16, K1 vale 3.985933831712888e+19 e cond vale 0.9502


K1 é maior que a coluna 18 pela coluna 17, K1 vale 3.985933831712888e+19 e cond vale 0.9753


K1 é maior que a coluna 18 pela coluna 19, K1 vale 3.985933831712888e+19 e cond vale 1.0244


K1 é maior que a coluna 18 pela coluna 20, K1 vale 3.985933831712888e+19 e cond vale 1.0485


K1 é maior que a coluna 18 pela coluna 21, K1 vale 3.985933831712888e+19 e cond vale 1.0723


K1 é maior que a coluna 18 pela coluna 22, K1 vale 3.985933831712888e+19 e cond vale 1.0959


K1 é maior que a coluna 18 pela coluna 23, K1 vale 3.985933831712888e+19 e cond vale 1.1192


K1 é maior que a coluna 18 pela coluna 24, K1 vale 3.985933


K1 é maior que a coluna 28 pela coluna 31, K1 vale 3.985933831712888e+19 e cond vale 1.0539


K1 é maior que a coluna 28 pela coluna 32, K1 vale 3.985933831712888e+19 e cond vale 1.0716


K1 é maior que a coluna 28 pela coluna 33, K1 vale 3.985933831712888e+19 e cond vale 1.0893


K1 é maior que a coluna 28 pela coluna 34, K1 vale 3.985933831712888e+19 e cond vale 1.1069


K1 é maior que a coluna 28 pela coluna 35, K1 vale 3.985933831712888e+19 e cond vale 1.1244


K1 é maior que a coluna 28 pela coluna 36, K1 vale 3.985933831712888e+19 e cond vale 1.1418


K1 é maior que a coluna 28 pela coluna 37, K1 vale 3.985933831712888e+19 e cond vale 1.1591


K1 é maior que a coluna 28 pela coluna 38, K1 vale 3.985933831712888e+19 e cond vale 1.1764


K1 é maior que a coluna 28 pela coluna 39, K1 vale 3.985933831712888e+19 e cond vale 1.1936


K1 é maior que a coluna 28 pela coluna 40, K1 vale 3.985933831712888e+19 e cond vale 1.2107


K1 é maior que a coluna 28 pela coluna 41, K1 vale 3.985933



K1 é maior que a coluna 38 pela coluna 61, K1 vale 3.985933831712888e+19 e cond vale 1.326


K1 é maior que a coluna 38 pela coluna 62, K1 vale 3.985933831712888e+19 e cond vale 1.3398


K1 é maior que a coluna 38 pela coluna 63, K1 vale 3.985933831712888e+19 e cond vale 1.3536


K1 é maior que a coluna 38 pela coluna 64, K1 vale 3.985933831712888e+19 e cond vale 1.3674


K1 é maior que a coluna 38 pela coluna 65, K1 vale 3.985933831712888e+19 e cond vale 1.3811


K1 é maior que a coluna 38 pela coluna 66, K1 vale 3.985933831712888e+19 e cond vale 1.3949


K1 é maior que a coluna 38 pela coluna 67, K1 vale 3.985933831712888e+19 e cond vale 1.4086


K1 é maior que a coluna 38 pela coluna 68, K1 vale 3.985933831712888e+19 e cond vale 1.4223


K1 é maior que a coluna 38 pela coluna 69, K1 vale 3.985933831712888e+19 e cond vale 1.436


K1 é maior que a coluna 38 pela coluna 70, K1 vale 3.985933831712888e+19 e cond vale 1.4496


K1 é maior que a coluna 38 pela coluna 71, K1 vale 3.9859338



K1 é maior que a coluna 48 pela coluna 65, K1 vale 3.985933831712888e+19 e cond vale 1.2072


K1 é maior que a coluna 48 pela coluna 66, K1 vale 3.985933831712888e+19 e cond vale 1.2192


K1 é maior que a coluna 48 pela coluna 67, K1 vale 3.985933831712888e+19 e cond vale 1.2312


K1 é maior que a coluna 48 pela coluna 68, K1 vale 3.985933831712888e+19 e cond vale 1.2432


K1 é maior que a coluna 48 pela coluna 69, K1 vale 3.985933831712888e+19 e cond vale 1.2552


K1 é maior que a coluna 48 pela coluna 70, K1 vale 3.985933831712888e+19 e cond vale 1.2671


K1 é maior que a coluna 48 pela coluna 71, K1 vale 3.985933831712888e+19 e cond vale 1.279


K1 é maior que a coluna 48 pela coluna 72, K1 vale 3.985933831712888e+19 e cond vale 1.291


K1 é maior que a coluna 48 pela coluna 73, K1 vale 3.985933831712888e+19 e cond vale 1.3029


K1 é maior que a coluna 48 pela coluna 74, K1 vale 3.985933831712888e+19 e cond vale 1.3147


K1 é maior que a coluna 48 pela coluna 75, K1 vale 3.9859338



K1 é maior que a coluna 58 pela coluna 67, K1 vale 3.985933831712888e+19 e cond vale 1.0967


K1 é maior que a coluna 58 pela coluna 68, K1 vale 3.985933831712888e+19 e cond vale 1.1073


K1 é maior que a coluna 58 pela coluna 69, K1 vale 3.985933831712888e+19 e cond vale 1.118


K1 é maior que a coluna 58 pela coluna 70, K1 vale 3.985933831712888e+19 e cond vale 1.1286


K1 é maior que a coluna 58 pela coluna 71, K1 vale 3.985933831712888e+19 e cond vale 1.1393


K1 é maior que a coluna 58 pela coluna 72, K1 vale 3.985933831712888e+19 e cond vale 1.1499


K1 é maior que a coluna 58 pela coluna 73, K1 vale 3.985933831712888e+19 e cond vale 1.1605


K1 é maior que a coluna 58 pela coluna 74, K1 vale 3.985933831712888e+19 e cond vale 1.1711


K1 é maior que a coluna 58 pela coluna 75, K1 vale 3.985933831712888e+19 e cond vale 1.1816


K1 é maior que a coluna 58 pela coluna 76, K1 vale 3.985933831712888e+19 e cond vale 1.1922


K1 é maior que a coluna 58 pela coluna 77, K1 vale 3.985933


K1 é maior que a coluna 68 pela coluna 62, K1 vale 3.985933831712888e+19 e cond vale 0.942


K1 é maior que a coluna 68 pela coluna 63, K1 vale 3.985933831712888e+19 e cond vale 0.9517


K1 é maior que a coluna 68 pela coluna 64, K1 vale 3.985933831712888e+19 e cond vale 0.9614


K1 é maior que a coluna 68 pela coluna 65, K1 vale 3.985933831712888e+19 e cond vale 0.9711


K1 é maior que a coluna 68 pela coluna 66, K1 vale 3.985933831712888e+19 e cond vale 0.9807


K1 é maior que a coluna 68 pela coluna 67, K1 vale 3.985933831712888e+19 e cond vale 0.9904


K1 é maior que a coluna 68 pela coluna 69, K1 vale 3.985933831712888e+19 e cond vale 1.0096


K1 é maior que a coluna 68 pela coluna 70, K1 vale 3.985933831712888e+19 e cond vale 1.0192


K1 é maior que a coluna 68 pela coluna 71, K1 vale 3.985933831712888e+19 e cond vale 1.0288


K1 é maior que a coluna 68 pela coluna 72, K1 vale 3.985933831712888e+19 e cond vale 1.0384


K1 é maior que a coluna 68 pela coluna 73, K1 vale 3.9859338


K1 é maior que a coluna 78 pela coluna 68, K1 vale 3.985933831712888e+19 e cond vale 0.9127


K1 é maior que a coluna 78 pela coluna 69, K1 vale 3.985933831712888e+19 e cond vale 0.9214


K1 é maior que a coluna 78 pela coluna 70, K1 vale 3.985933831712888e+19 e cond vale 0.9302


K1 é maior que a coluna 78 pela coluna 71, K1 vale 3.985933831712888e+19 e cond vale 0.939


K1 é maior que a coluna 78 pela coluna 72, K1 vale 3.985933831712888e+19 e cond vale 0.9477


K1 é maior que a coluna 78 pela coluna 73, K1 vale 3.985933831712888e+19 e cond vale 0.9565


K1 é maior que a coluna 78 pela coluna 74, K1 vale 3.985933831712888e+19 e cond vale 0.9652


K1 é maior que a coluna 78 pela coluna 75, K1 vale 3.985933831712888e+19 e cond vale 0.9739


K1 é maior que a coluna 78 pela coluna 76, K1 vale 3.985933831712888e+19 e cond vale 0.9826


K1 é maior que a coluna 78 pela coluna 77, K1 vale 3.985933831712888e+19 e cond vale 0.9913


K1 é maior que a coluna 78 pela coluna 79, K1 vale 3.9859338



K1 é maior que a coluna 88 pela coluna 92, K1 vale 3.985933831712888e+19 e cond vale 1.0317


K1 é maior que a coluna 88 pela coluna 93, K1 vale 3.985933831712888e+19 e cond vale 1.0396


K1 é maior que a coluna 88 pela coluna 94, K1 vale 3.985933831712888e+19 e cond vale 1.0475


K1 é maior que a coluna 88 pela coluna 95, K1 vale 3.985933831712888e+19 e cond vale 1.0554


K1 é maior que a coluna 88 pela coluna 96, K1 vale 3.985933831712888e+19 e cond vale 1.0632


K1 é maior que a coluna 88 pela coluna 97, K1 vale 3.985933831712888e+19 e cond vale 1.0711


K1 é maior que a coluna 88 pela coluna 98, K1 vale 3.985933831712888e+19 e cond vale 1.079


K1 é maior que a coluna 88 pela coluna 99, K1 vale 3.985933831712888e+19 e cond vale 1.0869


K1 é maior que a coluna 89 pela coluna 0, K1 vale 3.985933831712888e+19 e cond vale 0.1446


K1 é maior que a coluna 89 pela coluna 1, K1 vale 3.985933831712888e+19 e cond vale 0.1787


K1 é maior que a coluna 89 pela coluna 2, K1 vale 3.985933831

In [48]:
def checa_cond(A,invA, w):
    K1 = utils.norma_mat1(invA)*utils.norma_mat1(A)
    
    mat_aux = np.dot(invA,w)
    
    cond = utils.norma_mat1(A)*utils.norma_mat1(mat_aux)/utils.norma_mat1(w)
    
    print(K1, cond)
    
    return K1 > cond

In [49]:
for i in range(10):
    v = [np.random.randint(100),np.random.randint(100),np.random.randint(100)]
    print(v)
    checa_cond(H,inv_house, v)
    print("\n")

[86, 22, 27]


ValueError: shapes (100,100) and (3,) not aligned: 100 (dim 1) != 3 (dim 0)