In [149]:
import utils
import householder as hh

import importlib
import numpy as np
importlib.reload(utils)
importlib.reload(hh)

<module 'householder' from 'C:\\Users\\Hideki\\Desktop\\Github\\unicamp\\MS512\\lib\\householder.py'>

# Inicializando uma matriz de hilbert

In [150]:
H = utils.getHilbert(4).tolist()
H

[[1.0, 0.5, 0.3333333333333333, 0.25],
 [0.5, 0.3333333333333333, 0.25, 0.2],
 [0.3333333333333333, 0.25, 0.2, 0.16666666666666666],
 [0.25, 0.2, 0.16666666666666666, 0.14285714285714285]]

# Fazendo a fatoração QR pela classe construida

In [151]:
house = hh.HouseHolder([1,2,3])
Q2, R2= house.getQR(H)

# Fazendo a fatoração QR pela lib do scipy

In [152]:
import scipy
import scipy.linalg

Q, R = scipy.linalg.qr(H)

# Comparando as matrizes Q

In [153]:
print("Matriz pelo scipy")
print(Q.round(4))
print('\n')
print("Matriz pela classe")
print(Q2.round(4))
print('\n')
print("Diferença")
print((Q-Q2).round(4))

Matriz pelo scipy
[[-0.8381  0.5226 -0.154  -0.0263]
 [-0.4191 -0.4417  0.7278  0.3157]
 [-0.2794 -0.5288 -0.1395 -0.7892]
 [-0.2095 -0.5021 -0.6536  0.5261]]


Matriz pela classe
[[-0.8381  0.5226 -0.154  -0.0263]
 [-0.4191 -0.4417  0.7278  0.3157]
 [-0.2794 -0.5288 -0.1395 -0.7892]
 [-0.2095 -0.5021 -0.6536  0.5261]]


Diferença
[[ 0. -0.  0. -0.]
 [ 0.  0. -0.  0.]
 [ 0. -0.  0. -0.]
 [ 0. -0. -0. -0.]]


In [154]:
print("Matriz pelo scipy")
print(R.round(4))
print('\n')
print("Matriz pela classe")
print(R2.round(4))
print('\n')
print("Diferença")
print((R-R2).round(4))

Matriz pelo scipy
[[ -1.19320000e+00  -6.70500000e-01  -4.74900000e-01  -3.69800000e-01]
 [  0.00000000e+00  -1.18500000e-01  -1.25700000e-01  -1.17500000e-01]
 [  0.00000000e+00   0.00000000e+00  -6.20000000e-03  -9.60000000e-03]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   2.00000000e-04]]


Matriz pela classe
[[ -1.19320000e+00  -6.70500000e-01  -4.74900000e-01  -3.69800000e-01]
 [  0.00000000e+00  -1.18500000e-01  -1.25700000e-01  -1.17500000e-01]
 [ -0.00000000e+00   0.00000000e+00  -6.20000000e-03  -9.60000000e-03]
 [ -0.00000000e+00  -0.00000000e+00   0.00000000e+00   2.00000000e-04]]


Diferença
[[ 0.  0.  0.  0.]
 [-0. -0.  0. -0.]
 [ 0. -0.  0.  0.]
 [ 0.  0. -0. -0.]]


# Testando propriedades de Q

In [155]:
np.dot(Q,utils.transposta(Q)).round(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1., -0.,  0.],
       [ 0., -0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

# Nossa fatoração está boa

# Testando a resolução de sistema linear

In [249]:
import utils
import householder as hh

import importlib
import numpy as np
importlib.reload(utils)
importlib.reload(hh)

<module 'householder' from 'C:\\Users\\Hideki\\Desktop\\Github\\unicamp\\MS512\\lib\\householder.py'>

In [250]:
i = 5
H = utils.getHilbert(i)
H

array([[ 1.        ,  0.5       ,  0.33333333,  0.25      ,  0.2       ],
       [ 0.5       ,  0.33333333,  0.25      ,  0.2       ,  0.16666667],
       [ 0.33333333,  0.25      ,  0.2       ,  0.16666667,  0.14285714],
       [ 0.25      ,  0.2       ,  0.16666667,  0.14285714,  0.125     ],
       [ 0.2       ,  0.16666667,  0.14285714,  0.125     ,  0.11111111]])

In [251]:
house = hh.HouseHolder(H)

In [252]:
inv_house = house.resolve_sistema(np.eye(i))
inv_house

array([[  2.50000000e+01,  -3.00000000e+02,   1.05000000e+03,
         -1.40000000e+03,   6.30000000e+02],
       [ -3.00000000e+02,   4.80000000e+03,  -1.89000000e+04,
          2.68800000e+04,  -1.26000000e+04],
       [  1.05000000e+03,  -1.89000000e+04,   7.93800000e+04,
         -1.17600000e+05,   5.67000000e+04],
       [ -1.40000000e+03,   2.68800000e+04,  -1.17600000e+05,
          1.79200000e+05,  -8.82000000e+04],
       [  6.30000000e+02,  -1.26000000e+04,   5.67000000e+04,
         -8.82000000e+04,   4.41000000e+04]])

In [253]:
np.dot(H,inv_house).round(4)

array([[ 1.,  0., -0.,  0., -0.],
       [-0.,  1., -0.,  0., -0.],
       [-0.,  0.,  1.,  0., -0.],
       [-0.,  0.,  0.,  1., -0.],
       [-0., -0.,  0.,  0.,  1.]])

In [254]:
Q, R = scipy.linalg.qr(H)

In [255]:
print(Q)
print('\n')
print(R)

[[-0.8265843   0.53335463 -0.17530535  0.03910207  0.00550474]
 [-0.41329215 -0.37405354  0.7172624  -0.40334521 -0.11009471]
 [-0.2755281  -0.46294598  0.05766473  0.67896462  0.49542619]
 [-0.20664607 -0.44331911 -0.35262561  0.20615371 -0.77066296]
 [-0.16531686 -0.40591376 -0.57195511 -0.57644719  0.38533148]]


[[ -1.20979796e+00  -6.88820248e-01  -4.92014463e-01  -3.85411329e-01
   -3.17759341e-01]
 [  0.00000000e+00  -1.30059810e-01  -1.40191904e-01  -1.32700236e-01
   -1.22322889e-01]
 [  0.00000000e+00   0.00000000e+00  -8.06537859e-03  -1.26325450e-02
   -1.49082870e-02]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00  -3.38121669e-04
   -6.89314703e-04]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    8.73767527e-06]]


In [257]:
inf = np.linalg.solve(R, np.dot(utils.transposta(Q),np.eye(i)))
inf

array([[  2.50000000e+01,  -3.00000000e+02,   1.05000000e+03,
         -1.40000000e+03,   6.30000000e+02],
       [ -3.00000000e+02,   4.80000000e+03,  -1.89000000e+04,
          2.68800000e+04,  -1.26000000e+04],
       [  1.05000000e+03,  -1.89000000e+04,   7.93800000e+04,
         -1.17600000e+05,   5.67000000e+04],
       [ -1.40000000e+03,   2.68800000e+04,  -1.17600000e+05,
          1.79200000e+05,  -8.82000000e+04],
       [  6.30000000e+02,  -1.26000000e+04,   5.67000000e+04,
         -8.82000000e+04,   4.41000000e+04]])

In [258]:
np.dot(H,inf).round(4)

array([[ 1.,  0., -0.,  0., -0.],
       [ 0.,  1.,  0., -0.,  0.],
       [ 0., -0.,  1.,  0.,  0.],
       [ 0., -0.,  0.,  1.,  0.],
       [ 0., -0.,  0., -0.,  1.]])

In [259]:
invof = np.linalg.solve(H,np.eye(i)) 
invof

array([[  2.50000000e+01,  -3.00000000e+02,   1.05000000e+03,
         -1.40000000e+03,   6.30000000e+02],
       [ -3.00000000e+02,   4.80000000e+03,  -1.89000000e+04,
          2.68800000e+04,  -1.26000000e+04],
       [  1.05000000e+03,  -1.89000000e+04,   7.93800000e+04,
         -1.17600000e+05,   5.67000000e+04],
       [ -1.40000000e+03,   2.68800000e+04,  -1.17600000e+05,
          1.79200000e+05,  -8.82000000e+04],
       [  6.30000000e+02,  -1.26000000e+04,   5.67000000e+04,
         -8.82000000e+04,   4.41000000e+04]])

In [260]:
np.dot(H,invof).round(4)

array([[ 1., -0.,  0.,  0., -0.],
       [ 0.,  1., -0., -0., -0.],
       [ 0., -0.,  1.,  0.,  0.],
       [ 0., -0.,  0.,  1.,  0.],
       [-0.,  0., -0.,  0.,  1.]])