In [197]:
import utils
import householder as hh

import importlib
import numpy as np
importlib.reload(utils)
importlib.reload(hh)

<module 'householder' from 'C:\\Users\\Hideki\\Desktop\\Github\\unicamp\\MS512\\lib\\householder.py'>

In [91]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [144]:
a = [i[:] for i in y]
a[0][0] = 1
y

[[3], [2], [1]]

In [149]:
utils.transposta(y)[0]

error: A matriz não é quadrada


array([3, 2, 1])

In [221]:
x = [1,2,3]
y = [[3],[2],[1]]

In [222]:
np.dot(y,[x])

array([[3, 6, 9],
       [2, 4, 6],
       [1, 2, 3]])

In [223]:
utils.transposta([x])

error: A matriz não é quadrada


array([[1],
       [2],
       [3]])

In [107]:
utils.norma2(utils.transposta(y))

error: A matriz não é quadrada


3.7416573867739413

In [108]:
len(y)

3

In [109]:
len(x)

1

In [95]:
np.dot(y,x)

array([[3, 6, 9],
       [2, 4, 6],
       [1, 2, 3]])

In [105]:
np.dot(Q,x[0])

array([-11., -10.,  -9.])

In [193]:
result = np.zeros([3,3])
result

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [208]:
Q.shape

(3, 3)

In [213]:
Q[:][2]

array([-0.26726124, -0.07928651,  0.96035675])

In [207]:
house.padding(house.padding(Q,4),5)

array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        , -0.80178373, -0.53452248, -0.26726124],
       [ 0.        ,  0.        , -0.53452248,  0.84142698, -0.07928651],
       [ 0.        ,  0.        , -0.26726124, -0.07928651,  0.96035675]])

In [172]:
test = [[1],[1]]

In [204]:
house = hh.HouseHolder(np.eye(3))

Q, u, gamma = house.getQ(y)

error: A matriz não é quadrada
error: A matriz não é quadrada


In [205]:
Q

array([[-0.80178373, -0.53452248, -0.26726124],
       [-0.53452248,  0.84142698, -0.07928651],
       [-0.26726124, -0.07928651,  0.96035675]])

In [180]:
u

[[1.0], [0.41421356237309509]]

In [181]:
gamma

array([[-1.41421356],
       [ 0.        ]])

In [124]:
y

[[6.7416573867739409], [2], [1]]

In [3]:
utils.produto_interno(x,y)

[3, 4, 3]

In [4]:
utils.norma2(x)

3.7416573867739413

In [5]:
x = np.array([[1,2,3],[2,3,4],[1,1,1]])
y = np.array([[1,2,3],[2,3,4]])

x1 = np.array([[1,1,0,3],[0,-1,-1,-5],[0,0,3,13],[0,0,0,-13]])
b1 = [4,-7,13,-13]

In [6]:
x

array([[1, 2, 3],
       [2, 3, 4],
       [1, 1, 1]])

In [7]:
y

array([[1, 2, 3],
       [2, 3, 4]])

In [8]:
utils.transposta(x)

array([[1, 2, 1],
       [2, 3, 1],
       [3, 4, 1]])

In [9]:
utils.transposta(y)

error: A matriz não é quadrada


array([[1, 2],
       [2, 3],
       [3, 4]])

In [13]:
utils.retroSub(x1,b1)

array([-1.,  2.,  0.,  1.])

In [11]:
z = np.zeros(3)

In [109]:
z[2]

0.0

In [127]:
for i in range(1,1):
    print(i)