In [1]:
import utils
import householder as hh

import importlib
import numpy as np
importlib.reload(utils)
importlib.reload(hh)

<module 'householder' from 'C:\\Users\\Hideki\\Desktop\\Github\\unicamp\\MS512\\lib\\householder.py'>

# Inicializando uma matriz de hilbert

In [2]:
H = utils.getHilbert(13)
H

array([[ 1.        ,  0.5       ,  0.33333333,  0.25      ,  0.2       ,
         0.16666667,  0.14285714,  0.125     ,  0.11111111,  0.1       ,
         0.09090909,  0.08333333,  0.07692308],
       [ 0.5       ,  0.33333333,  0.25      ,  0.2       ,  0.16666667,
         0.14285714,  0.125     ,  0.11111111,  0.1       ,  0.09090909,
         0.08333333,  0.07692308,  0.07142857],
       [ 0.33333333,  0.25      ,  0.2       ,  0.16666667,  0.14285714,
         0.125     ,  0.11111111,  0.1       ,  0.09090909,  0.08333333,
         0.07692308,  0.07142857,  0.06666667],
       [ 0.25      ,  0.2       ,  0.16666667,  0.14285714,  0.125     ,
         0.11111111,  0.1       ,  0.09090909,  0.08333333,  0.07692308,
         0.07142857,  0.06666667,  0.0625    ],
       [ 0.2       ,  0.16666667,  0.14285714,  0.125     ,  0.11111111,
         0.1       ,  0.09090909,  0.08333333,  0.07692308,  0.07142857,
         0.06666667,  0.0625    ,  0.05882353],
       [ 0.16666667,  0.142857

In [3]:
utils.norma_mat1(H)

3.1801337551337552

# Fazendo a fatoração QR pela classe construida

In [4]:
house = hh.HouseHolder([1,2,3])
Q2, R2= house.getQR(H)

# Fazendo a fatoração QR pela lib do scipy

In [5]:
import scipy
import scipy.linalg

Q, R = scipy.linalg.qr(H)

# Comparando as matrizes Q

In [6]:
print("Matriz pelo scipy")
print(Q.round(4))
print('\n')
print("Matriz pela classe")
print(Q2.round(4))
print('\n')
print("Diferença")
print((Q-Q2).round(4))

Matriz pelo scipy
[[ -7.97900000e-01   5.53400000e-01   2.25600000e-01  -7.58000000e-02
    2.23000000e-02  -5.80000000e-03  -1.40000000e-03   3.00000000e-04
   -1.00000000e-04  -0.00000000e+00  -0.00000000e+00   0.00000000e+00
   -0.00000000e+00]
 [ -3.98900000e-01  -2.29500000e-01  -6.38200000e-01   5.28100000e-01
   -2.90600000e-01   1.24100000e-01   4.35000000e-02  -1.29000000e-02
    3.20000000e-03   7.00000000e-04   1.00000000e-04  -0.00000000e+00
    0.00000000e+00]
 [ -2.66000000e-01  -3.21700000e-01  -3.09800000e-01  -2.61200000e-01
    5.66100000e-01  -4.90800000e-01  -2.86400000e-01   1.26900000e-01
   -4.46000000e-02  -1.26000000e-02  -2.80000000e-03   5.00000000e-04
   -1.00000000e-04]
 [ -1.99500000e-01  -3.17200000e-01  -7.04000000e-02  -4.10700000e-01
    1.77500000e-01   3.32100000e-01   5.41400000e-01  -4.31700000e-01
    2.34400000e-01   9.43000000e-02   2.86000000e-02  -6.30000000e-03
    9.00000000e-04]
 [ -1.59600000e-01  -2.94200000e-01   7.18000000e-02  -3.33500

In [9]:
print("Matriz pelo scipy")
print(R.round(4))
print('\n')
print("Matriz pela classe")
print(R2.round(4))
print('\n')
print("Diferença")
print((R-R2).round(4))

Matriz pelo scipy
[[ -1.25340000e+00  -7.40900000e-01  -5.43300000e-01  -4.34200000e-01
   -3.63800000e-01  -3.14100000e-01  -2.76900000e-01  -2.47900000e-01
   -2.24700000e-01  -2.05500000e-01  -1.89500000e-01  -1.75800000e-01
   -1.64100000e-01]
 [  0.00000000e+00  -1.64600000e-01  -1.87200000e-01  -1.84500000e-01
   -1.75600000e-01  -1.65500000e-01  -1.55600000e-01  -1.46300000e-01
   -1.37900000e-01  -1.30300000e-01  -1.23400000e-01  -1.17100000e-01
   -1.11500000e-01]
 [  0.00000000e+00   0.00000000e+00   1.52000000e-02   2.54000000e-02
    3.15000000e-02   3.51000000e-02   3.71000000e-02   3.81000000e-02
    3.84000000e-02   3.83000000e-02   3.79000000e-02   3.74000000e-02
    3.67000000e-02]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.20000000e-03
    2.60000000e-03   3.90000000e-03   4.90000000e-03   5.80000000e-03
    6.50000000e-03   7.00000000e-03   7.40000000e-03   7.70000000e-03
    7.90000000e-03]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000

# Testando propriedades de Q

In [10]:
np.dot(Q,utils.transposta(Q)).round(4)

array([[ 1.,  0.,  0.,  0.,  0.,  0., -0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0., -0., -0., -0., -0.,  0., -0.,  0., -0.,  0., -0.],
       [ 0.,  0.,  1.,  0., -0., -0., -0.,  0.,  0.,  0.,  0., -0., -0.],
       [ 0., -0.,  0.,  1., -0.,  0.,  0., -0., -0., -0., -0.,  0.,  0.],
       [ 0., -0., -0., -0.,  1., -0., -0., -0.,  0.,  0.,  0., -0.,  0.],
       [ 0., -0., -0.,  0., -0.,  1.,  0.,  0., -0.,  0., -0.,  0., -0.],
       [-0., -0., -0.,  0., -0.,  0.,  1., -0.,  0.,  0.,  0., -0., -0.],
       [ 0.,  0.,  0., -0., -0.,  0., -0.,  1., -0.,  0.,  0., -0., -0.],
       [ 0., -0.,  0., -0.,  0., -0.,  0., -0.,  1., -0., -0.,  0.,  0.],
       [ 0.,  0.,  0., -0.,  0.,  0.,  0.,  0., -0.,  1.,  0., -0.,  0.],
       [ 0., -0.,  0., -0.,  0., -0.,  0.,  0., -0.,  0.,  1.,  0., -0.],
       [ 0.,  0., -0.,  0., -0.,  0., -0., -0.,  0., -0.,  0.,  1.,  0.],
       [ 0.,  0., -0.,  0.,  0., -0., -0., -0.,  0.,  0., -0.,  0.,  1.]])

# Nossa fatoração está boa

# Testando a resolução de sistema linear

In [117]:
import utils
import householder as hh

import importlib
import numpy as np
importlib.reload(utils)
importlib.reload(hh)

<module 'householder' from 'C:\\Users\\Hideki\\Desktop\\Github\\unicamp\\MS512\\lib\\householder.py'>

In [118]:
i = 3
H = utils.getHilbert(i)
H

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.5       ,  0.33333333,  0.25      ],
       [ 0.33333333,  0.25      ,  0.2       ]])

In [119]:
house = hh.HouseHolder(H)

In [120]:
inv_house = house.resolve_sistema(np.eye(i))
inv_house

array([[   9.,  -36.,   30.],
       [ -36.,  192., -180.],
       [  30., -180.,  180.]])

In [121]:
np.dot(H,inv_house).round(11)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0., -0.,  1.]])

In [122]:
Q, R = scipy.linalg.qr(H)

In [123]:
print(Q)
print('\n')
print(R)

[[-0.85714286  0.50160492  0.11704115]
 [-0.42857143 -0.56848557 -0.70224688]
 [-0.28571429 -0.65208639  0.70224688]]


[[-1.16666667 -0.64285714 -0.45      ]
 [ 0.         -0.10171433 -0.10533703]
 [ 0.          0.          0.00390137]]


In [124]:
inf = np.linalg.solve(R, np.dot(utils.transposta(Q),np.eye(i)))
inf

array([[   9.,  -36.,   30.],
       [ -36.,  192., -180.],
       [  30., -180.,  180.]])

In [125]:
np.dot(H,inf).round(4)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [126]:
invof = np.linalg.solve(H,np.eye(i)) 
invof

array([[   9.,  -36.,   30.],
       [ -36.,  192., -180.],
       [  30., -180.,  180.]])

In [127]:
np.dot(H,invof).round(4)

array([[ 1.,  0., -0.],
       [-0.,  1.,  0.],
       [-0.,  0.,  1.]])

# Número de condicionamento

In [131]:
importlib.reload(utils)
n = 3
H = utils.getHilbert(n)
H

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.5       ,  0.33333333,  0.25      ],
       [ 0.33333333,  0.25      ,  0.2       ]])

In [132]:
house = hh.HouseHolder(H)
inv_house = house.resolve_sistema(np.eye(n))
inv_house

array([[   9.,  -36.,   30.],
       [ -36.,  192., -180.],
       [  30., -180.,  180.]])

In [133]:
np.dot(H,inv_house)

array([[  1.00000000e+00,   8.06762065e-15,   1.40628250e-15],
       [  8.88178420e-16,   1.00000000e+00,   0.00000000e+00],
       [  1.57651669e-15,  -1.99840144e-15,   1.00000000e+00]])

In [134]:
Q, R = house.getQR(H)

In [135]:
Q

array([[-0.85714286,  0.50160492,  0.11704115],
       [-0.42857143, -0.56848557, -0.70224688],
       [-0.28571429, -0.65208639,  0.70224688]])

In [136]:
R

array([[ -1.16666667e+00,  -6.42857143e-01,  -4.50000000e-01],
       [ -8.13921017e-17,  -1.01714330e-01,  -1.05337032e-01],
       [ -5.85154474e-17,  -6.10288507e-18,   3.90137157e-03]])

In [137]:
np.dot(utils.transposta(Q),Q).round(4)

array([[ 1., -0.,  0.],
       [-0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [138]:
K1 = utils.norma_mat1(inv_house)*utils.norma_mat1(H)
K1

748.00000000000625

In [139]:
utils.norma_mat1(H[:,0])

1.8333333333333333

In [140]:
sum([np.abs(v) for v in H[:,0]])

1.8333333333333333

In [141]:
for k in range(n):
    for j in range(n):
        if(k!=j):
            ni = utils.norma_mat1(H[:,k])
            nj = utils.norma_mat1(H[:,j])

            cond = ni/nj

            if(K1 > cond):
                print(f"\nK1 é maior que a coluna {k} pela coluna {j}, K1 vale {K1.round(4)} e cond vale {cond.round(4)}\n")
            else:
                print("nop")


K1 é maior que a coluna 0 pela coluna 1, K1 vale 748.0 e cond vale 1.6923


K1 é maior que a coluna 0 pela coluna 2, K1 vale 748.0 e cond vale 2.3404


K1 é maior que a coluna 1 pela coluna 0, K1 vale 748.0 e cond vale 0.5909


K1 é maior que a coluna 1 pela coluna 2, K1 vale 748.0 e cond vale 1.383


K1 é maior que a coluna 2 pela coluna 0, K1 vale 748.0 e cond vale 0.4273


K1 é maior que a coluna 2 pela coluna 1, K1 vale 748.0 e cond vale 0.7231



In [142]:
def checa_cond(A,invA, w):
    K1 = utils.norma_mat1(invA)*utils.norma_mat1(A)
    
    mat_aux = np.dot(invA,w)
    
    cond = utils.norma_mat1(A)*utils.norma_mat1(mat_aux)/utils.norma_mat1(w)
    
    print(K1)
    print(' : ')
    print(cond)
    
    return K1 > cond

In [143]:
import random

for i in range(10):
    v = random.sample(range(100),  n)
    print(v)
    checa_cond(H,inv_house, v)
    print("\n")

[36, 89, 49]
748.0
 : 
152.798850575


[12, 6, 58]
748.0
 : 
508.315789474


[72, 97, 43]
748.0
 : 
150.523584906


[61, 4, 49]
748.0
 : 
354.653508772


[74, 31, 83]
748.0
 : 
246.446808511


[10, 87, 17]
748.0
 : 
452.157894737


[86, 16, 40]
748.0
 : 
200.401408451


[79, 68, 21]
748.0
 : 
148.729166667


[62, 87, 30]
748.0
 : 
196.094972067


[72, 40, 13]
748.0
 : 
85.8




# Checando para n maiores

In [113]:
importlib.reload(utils)
n = 6
H = utils.getHilbert(n)
H
house = hh.HouseHolder(H)
inv_house = house.resolve_sistema(np.eye(n))

np.dot(H,inv_house).round(5)

array([[ 1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0., -0.,  0., -0.],
       [ 0.,  0.,  1., -0.,  0., -0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.],
       [ 0., -0.,  0., -0.,  1., -0.],
       [ 0., -0.,  0., -0.,  0.,  1.]])

In [146]:
importlib.reload(utils)

n = 12

H = utils.getHilbert(n)
H
house = hh.HouseHolder(H)
inv_house = house.resolve_sistema(np.eye(n))

np.dot(H,inv_house).round(2)

array([[ 1.  ,  0.  , -0.  ,  0.  ,  0.  ,  0.01, -0.05,  0.04, -0.12,
         0.  ,  0.03,  0.  ],
       [ 0.  ,  1.  , -0.  , -0.  ,  0.  , -0.01, -0.01, -0.07,  0.  ,
         0.  , -0.03,  0.  ],
       [-0.  ,  0.  ,  1.  ,  0.  , -0.  ,  0.02, -0.07,  0.04, -0.12,
         0.  , -0.06,  0.01],
       [-0.  ,  0.  , -0.  ,  1.  , -0.  ,  0.02, -0.06,  0.07, -0.12,
         0.12, -0.03,  0.  ],
       [-0.  ,  0.  , -0.  ,  0.  ,  0.99,  0.02, -0.09,  0.11, -0.25,
         0.06, -0.03,  0.01],
       [-0.  ,  0.  , -0.  ,  0.  , -0.  ,  1.01, -0.04,  0.03, -0.06,
         0.  , -0.03,  0.  ],
       [-0.  ,  0.  , -0.  ,  0.  , -0.  ,  0.01,  0.96,  0.03, -0.12,
         0.  , -0.03,  0.  ],
       [-0.  ,  0.  , -0.  ,  0.  , -0.  ,  0.02, -0.06,  1.1 , -0.12,
         0.06, -0.03,  0.  ],
       [-0.  ,  0.  , -0.  ,  0.  , -0.  ,  0.02, -0.05,  0.04,  0.94,
         0.06, -0.03,  0.01],
       [-0.  ,  0.  , -0.  ,  0.  , -0.  ,  0.02, -0.04,  0.06, -0.06,
         1.  , -0.03

In [147]:
importlib.reload(utils)

n = 15

H = utils.getHilbert(n)
H
house = hh.HouseHolder(H)
inv_house = house.resolve_sistema(np.eye(n))

np.dot(H,inv_house).round(2)

array([[ 1.  ,  0.  , -0.  ,  0.01, -0.05,  0.32, -2.1 ,  3.91, -2.8 ,
         5.68, -0.84, -2.09,  0.8 , -0.42, -0.04],
       [-0.  ,  1.  , -0.  ,  0.  , -0.04,  0.27, -0.94,  2.34, -3.41,
         4.41, -1.4 , -0.31,  0.75, -0.8 ,  0.17],
       [ 0.  , -0.  ,  1.  , -0.  ,  0.01, -0.  ,  0.41, -1.05,  0.65,
         0.03, -0.34,  2.02, -1.62,  0.85, -0.06],
       [-0.  ,  0.  , -0.  ,  1.  , -0.02,  0.13, -0.41,  1.11, -0.94,
         2.38, -0.7 ,  0.21, -0.03, -0.25,  0.09],
       [-0.  ,  0.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.01,  0.08,  0.69,
         0.44, -0.16,  0.76, -0.43, -0.02,  0.02],
       [-0.  , -0.  , -0.  , -0.  , -0.01,  1.04, -0.21,  0.3 , -0.52,
         0.6 ,  0.02,  0.04,  0.66, -0.1 ,  0.08],
       [ 0.  , -0.  ,  0.  , -0.  ,  0.02, -0.11,  1.37, -0.7 ,  1.34,
        -0.6 , -0.23,  1.63, -1.29,  0.59, -0.06],
       [ 0.  , -0.  ,  0.  , -0.  ,  0.01, -0.04,  0.31,  0.28,  1.09,
        -0.21,  0.35,  0.68, -0.18, -0.15, -0.01],
       [ 0.  , -0.  ,  0

# Checando numero de condicionamento para n grandes

In [149]:
importlib.reload(utils)

n = 6

H = utils.getHilbert(n)
H
house = hh.HouseHolder(H)
inv_house = house.resolve_sistema(np.eye(n))

K1 = utils.norma_mat1(inv_house)*utils.norma_mat1(H)
K1
for k in range(n):
    for j in range(n):
        if(k!=j):
            ni = utils.norma_mat1(H[:,k])
            nj = utils.norma_mat1(H[:,j])

            cond = ni/nj

            if(K1 > cond):
                print(f"\nK1 é maior que a coluna {k} pela coluna {j}, K1 vale {K1.round(4)} e cond vale {cond.round(4)}\n")
            else:
                print("nop")


K1 é maior que a coluna 0 pela coluna 1, K1 vale 29070279.0029 e cond vale 1.5381


K1 é maior que a coluna 0 pela coluna 2, K1 vale 29070279.0029 e cond vale 2.0117


K1 é maior que a coluna 0 pela coluna 3, K1 vale 29070279.0029 e cond vale 2.4607


K1 é maior que a coluna 0 pela coluna 4, K1 vale 29070279.0029 e cond vale 2.8972


K1 é maior que a coluna 0 pela coluna 5, K1 vale 29070279.0029 e cond vale 3.3263


K1 é maior que a coluna 1 pela coluna 0, K1 vale 29070279.0029 e cond vale 0.6501


K1 é maior que a coluna 1 pela coluna 2, K1 vale 29070279.0029 e cond vale 1.3079


K1 é maior que a coluna 1 pela coluna 3, K1 vale 29070279.0029 e cond vale 1.5998


K1 é maior que a coluna 1 pela coluna 4, K1 vale 29070279.0029 e cond vale 1.8836


K1 é maior que a coluna 1 pela coluna 5, K1 vale 29070279.0029 e cond vale 2.1626


K1 é maior que a coluna 2 pela coluna 0, K1 vale 29070279.0029 e cond vale 0.4971


K1 é maior que a coluna 2 pela coluna 1, K1 vale 29070279.0029 e cond vale 

In [150]:
import random

for i in range(10):
    v = random.sample(range(100),  n)
    print(v)
    checa_cond(H,inv_house, v)
    print("\n")

[36, 98, 72, 79, 85, 66]
29070279.0029
 : 
498687.115648


[27, 39, 74, 88, 16, 3]
29070279.0029
 : 
4844868.96971


[91, 67, 62, 90, 38, 8]
29070279.0029
 : 
2327170.21371


[83, 43, 7, 22, 49, 19]
29070279.0029
 : 
2855736.69984


[11, 93, 8, 18, 10, 6]
29070279.0029
 : 
2138052.37418


[2, 36, 92, 52, 62, 88]
29070279.0029
 : 
923415.833217


[7, 98, 29, 23, 40, 93]
29070279.0029
 : 
1242092.06185


[3, 34, 38, 5, 66, 41]
29070279.0029
 : 
8844820.43991


[49, 37, 20, 38, 60, 71]
29070279.0029
 : 
288942.451666


[23, 8, 98, 89, 54, 25]
29070279.0029
 : 
263994.72629




In [151]:
importlib.reload(utils)

n = 12

H = utils.getHilbert(n)
H
house = hh.HouseHolder(H)
inv_house = house.resolve_sistema(np.eye(n))

K1 = utils.norma_mat1(inv_house)*utils.norma_mat1(H)
K1
for k in range(n):
    for j in range(n):
        if(k!=j):
            ni = utils.norma_mat1(H[:,k])
            nj = utils.norma_mat1(H[:,j])

            cond = ni/nj

            if(K1 > cond):
                print(f"\nK1 é maior que a coluna {k} pela coluna {j}, K1 vale {K1.round(4)} e cond vale {cond.round(4)}\n")
            else:
                print("nop")


K1 é maior que a coluna 0 pela coluna 1, K1 vale 4.224371050571898e+16 e cond vale 1.4234


K1 é maior que a coluna 0 pela coluna 2, K1 vale 4.224371050571898e+16 e cond vale 1.7717


K1 é maior que a coluna 0 pela coluna 3, K1 vale 4.224371050571898e+16 e cond vale 2.0899


K1 é maior que a coluna 0 pela coluna 4, K1 vale 4.224371050571898e+16 e cond vale 2.3919


K1 é maior que a coluna 0 pela coluna 5, K1 vale 4.224371050571898e+16 e cond vale 2.6839


K1 é maior que a coluna 0 pela coluna 6, K1 vale 4.224371050571898e+16 e cond vale 2.9693


K1 é maior que a coluna 0 pela coluna 7, K1 vale 4.224371050571898e+16 e cond vale 3.2498


K1 é maior que a coluna 0 pela coluna 8, K1 vale 4.224371050571898e+16 e cond vale 3.5268


K1 é maior que a coluna 0 pela coluna 9, K1 vale 4.224371050571898e+16 e cond vale 3.8011


K1 é maior que a coluna 0 pela coluna 10, K1 vale 4.224371050571898e+16 e cond vale 4.0733


K1 é maior que a coluna 0 pela coluna 11, K1 vale 4.224371050571898e+16 e cond

In [152]:
import random

for i in range(10):
    v = random.sample(range(100),  n)
    print(v)
    checa_cond(H,inv_house, v)
    print("\n")

[27, 21, 16, 99, 46, 67, 29, 9, 58, 64, 40, 76]
4.22437105057e+16
 : 
1.14924944997e+15


[94, 67, 27, 43, 71, 41, 15, 81, 63, 61, 38, 36]
4.22437105057e+16
 : 
2.54884772191e+15


[4, 10, 44, 43, 35, 83, 40, 86, 87, 97, 84, 79]
4.22437105057e+16
 : 
1.8378815435e+15


[38, 61, 58, 91, 86, 53, 9, 93, 46, 4, 81, 77]
4.22437105057e+16
 : 
1.05756603315e+15


[19, 42, 75, 7, 88, 38, 87, 8, 61, 69, 29, 96]
4.22437105057e+16
 : 
3.06513571203e+15


[31, 8, 22, 91, 44, 5, 62, 43, 75, 13, 83, 3]
4.22437105057e+16
 : 
7.34949919621e+15


[59, 89, 46, 85, 67, 64, 73, 38, 50, 53, 56, 84]
4.22437105057e+16
 : 
9.33169932832e+14


[11, 47, 90, 15, 98, 85, 20, 62, 43, 86, 4, 82]
4.22437105057e+16
 : 
5.0829753439e+15


[19, 21, 43, 50, 82, 31, 13, 73, 12, 39, 6, 57]
4.22437105057e+16
 : 
7.22569669092e+15


[49, 66, 23, 76, 97, 58, 10, 94, 63, 67, 0, 79]
4.22437105057e+16
 : 
4.47604013791e+15




In [153]:
importlib.reload(utils)

n = 50

H = utils.getHilbert(n)
H
house = hh.HouseHolder(H)
inv_house = house.resolve_sistema(np.eye(n))

K1 = utils.norma_mat1(inv_house)*utils.norma_mat1(H)
K1
for k in range(n):
    for j in range(n):
        if(k!=j):
            ni = utils.norma_mat1(H[:,k])
            nj = utils.norma_mat1(H[:,j])

            cond = ni/nj

            if(K1 > cond):
                print(f"\nK1 é maior que a coluna {k} pela coluna {j}, K1 vale {K1.round(4)} e cond vale {cond.round(4)}\n")
            else:
                print("nop")


K1 é maior que a coluna 0 pela coluna 1, K1 vale 3.6293295662798578e+19 e cond vale 1.2786


K1 é maior que a coluna 0 pela coluna 2, K1 vale 3.6293295662798578e+19 e cond vale 1.481


K1 é maior que a coluna 0 pela coluna 3, K1 vale 3.6293295662798578e+19 e cond vale 1.6519


K1 é maior que a coluna 0 pela coluna 4, K1 vale 3.6293295662798578e+19 e cond vale 1.8054


K1 é maior que a coluna 0 pela coluna 5, K1 vale 3.6293295662798578e+19 e cond vale 1.9475


K1 é maior que a coluna 0 pela coluna 6, K1 vale 3.6293295662798578e+19 e cond vale 2.0815


K1 é maior que a coluna 0 pela coluna 7, K1 vale 3.6293295662798578e+19 e cond vale 2.2097


K1 é maior que a coluna 0 pela coluna 8, K1 vale 3.6293295662798578e+19 e cond vale 2.3331


K1 é maior que a coluna 0 pela coluna 9, K1 vale 3.6293295662798578e+19 e cond vale 2.4529


K1 é maior que a coluna 0 pela coluna 10, K1 vale 3.6293295662798578e+19 e cond vale 2.5696


K1 é maior que a coluna 0 pela coluna 11, K1 vale 3.6293295662798578e


K1 é maior que a coluna 22 pela coluna 2, K1 vale 3.6293295662798578e+19 e cond vale 0.3851


K1 é maior que a coluna 22 pela coluna 3, K1 vale 3.6293295662798578e+19 e cond vale 0.4296


K1 é maior que a coluna 22 pela coluna 4, K1 vale 3.6293295662798578e+19 e cond vale 0.4695


K1 é maior que a coluna 22 pela coluna 5, K1 vale 3.6293295662798578e+19 e cond vale 0.5064


K1 é maior que a coluna 22 pela coluna 6, K1 vale 3.6293295662798578e+19 e cond vale 0.5413


K1 é maior que a coluna 22 pela coluna 7, K1 vale 3.6293295662798578e+19 e cond vale 0.5746


K1 é maior que a coluna 22 pela coluna 8, K1 vale 3.6293295662798578e+19 e cond vale 0.6067


K1 é maior que a coluna 22 pela coluna 9, K1 vale 3.6293295662798578e+19 e cond vale 0.6379


K1 é maior que a coluna 22 pela coluna 10, K1 vale 3.6293295662798578e+19 e cond vale 0.6682


K1 é maior que a coluna 22 pela coluna 11, K1 vale 3.6293295662798578e+19 e cond vale 0.6979


K1 é maior que a coluna 22 pela coluna 12, K1 vale 3.6293

In [154]:
import random

for i in range(10):
    v = random.sample(range(100),  n)
    print(v)
    checa_cond(H,inv_house, v)
    print("\n")

[75, 11, 2, 22, 48, 99, 5, 44, 50, 31, 15, 81, 72, 33, 51, 91, 78, 12, 26, 95, 93, 58, 86, 7, 46, 64, 70, 34, 80, 45, 30, 1, 94, 97, 24, 41, 32, 73, 76, 19, 77, 87, 82, 84, 63, 21, 60, 79, 37, 67]
3.62932956628e+19
 : 
4.72133571444e+17


[49, 55, 45, 34, 44, 48, 95, 2, 14, 99, 60, 82, 19, 56, 66, 18, 96, 13, 38, 41, 68, 16, 81, 21, 20, 65, 36, 54, 86, 7, 76, 46, 8, 69, 63, 71, 53, 62, 58, 5, 26, 51, 88, 97, 94, 84, 40, 87, 59, 57]
3.62932956628e+19
 : 
7.17545710186e+17


[25, 37, 21, 47, 27, 96, 31, 88, 2, 34, 91, 49, 90, 76, 35, 53, 39, 11, 92, 4, 20, 78, 51, 32, 52, 22, 77, 12, 54, 3, 8, 87, 85, 29, 56, 5, 16, 0, 24, 7, 44, 69, 64, 80, 98, 46, 60, 99, 6, 83]
3.62932956628e+19
 : 
6.6840728099e+17


[20, 42, 2, 78, 62, 50, 77, 12, 57, 75, 4, 46, 56, 3, 98, 5, 30, 41, 44, 76, 32, 25, 13, 89, 55, 51, 6, 40, 49, 39, 82, 28, 21, 38, 0, 29, 73, 10, 69, 22, 59, 96, 97, 14, 9, 27, 43, 91, 65, 18]
3.62932956628e+19
 : 
4.42277293373e+17


[45, 19, 24, 18, 54, 31, 90, 7, 47, 29, 94, 89, 72, 